#!/usr/bin/env bash
MODEL_NAME=full_basis
MODEL_VERSION=1
HOST=localhost
PORT=8504
GRPCPORT=8505
running=false

##############
# This command starts an instance of tensorflow serving with the model in
# This directory
##############
echo "START THE SERVER"
tensorflow_model_server --rest_api_port=8504 --model_base_path=/home/aduster/eclipse-workspace/fort-bpsf/test/7_tensorflow_server/simplemodel --model_name="full_basis" --port 8505 &
tfs_pid=$!

echo "tensorflow_model_server --rest_api_port=8504 --model_base_path=/home/aduster/eclipse-workspace/fort-bpsf/test/7_tensorflow_server/simplemodel --model_name="full_basis" --port 8505"

##############
# This command gets the Model status
##############
# All Versions
echo "ALL VERSIONS"
echo "GET http://${HOST}:${PORT}/v1/models/${MODEL_NAME}"
GET http://${HOST}:${PORT}/v1/models/${MODEL_NAME}

echo "VERSION $MODEL_VERSION"
echo "GET http://${HOST}:${PORT}/v1/models/${MODEL_NAME}/versions/${MODEL_VERSION}"
GET http://${HOST}:${PORT}/v1/models/${MODEL_NAME}/versions/${MODEL_VERSION}

##############
# Model Metadata API
##############

echo
echo "METADATA"
echo "GET http://${HOST}:${PORT}/v1/models/${MODEL_NAME}/metadata"
GET http://${HOST}:${PORT}/v1/models/${MODEL_NAME}/metadata

